# Generated by Django 5.2.5 on 2025-10-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, verbose_name='Сервис')),
                ('start_downtime', models.DateTimeField(verbose_name='Дата и время начала работ')),
                ('end_downtime', models.DateTimeField(verbose_name='Дата и время окончания работ')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проведение работ на сервисе',
                'verbose_name_plural': 'Проведение работ на сервисе',
            },
        ),
    ]
