# Generated by Django 5.2.5 on 2025-12-28 09:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import downtimes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, verbose_name='Сервис')),
                ('start_downtime', models.DateTimeField(validators=[downtimes.validators.check_date], verbose_name='Дата и время начала работ')),
                ('end_downtime', models.DateTimeField(validators=[downtimes.validators.check_date], verbose_name='Дата и время окончания работ')),
                ('link_task', models.URLField(max_length=150, verbose_name='Ссылка на задачу')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('gsma_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник от ГСМАиЦП')),
            ],
            options={
                'verbose_name': 'Проведение работ на сервисе',
                'verbose_name_plural': 'Проведение работ на сервисе',
                'ordering': ('start_downtime',),
            },
        ),
        migrations.CreateModel(
            name='ReminderDowntime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_reminder', models.DateTimeField(verbose_name='Первое уведомление')),
                ('second_reminder', models.DateTimeField(blank=True, null=True, verbose_name='Второе уведомление')),
                ('success_reminder', models.BooleanField(default=False, verbose_name='Уведомления отправлены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано от')),
                ('downtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downtimes.downtime', verbose_name='Плановая работа')),
            ],
            options={
                'verbose_name': 'Напоминание по проведению работ',
                'verbose_name_plural': 'Напоминания по проведению работ',
            },
        ),
        migrations.AddConstraint(
            model_name='downtime',
            constraint=models.UniqueConstraint(fields=('gsma_employee', 'service', 'start_downtime', 'end_downtime'), name='unique_downtime'),
        ),
    ]
