# Generated by Django 5.2.5 on 2025-12-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderdowntime',
            name='downtime',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='downtimes.downtime', verbose_name='Плановая работа'),
        ),
    ]
