# Generated by Django 5.2.5 on 2025-10-13 11:07

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0002_downtime_gsma_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания записи'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='downtime',
            constraint=models.UniqueConstraint(fields=('gsma_employee', 'service', 'start_downtime', 'end_downtime'), name='unique_downtime'),
        ),
    ]
