# Generated by Django 5.2.5 on 2026-01-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0003_alter_reminderdowntime_downtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtime',
            options={'ordering': ('-start_downtime',), 'verbose_name': 'Проведение работ на сервисе', 'verbose_name_plural': 'Проведение работ на сервисе'},
        ),
    ]
