# Generated by Django 5.2.5 on 2025-10-14 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import downtimes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0003_downtime_created_at_downtime_unique_downtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='link_task',
            field=models.URLField(default=0, max_length=150, verbose_name='Ссылка на задачу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downtime',
            name='end_downtime',
            field=models.DateTimeField(validators=[downtimes.validators.check_date], verbose_name='Дата и время окончания работ'),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='gsma_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник от ГСМАиЦП'),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='start_downtime',
            field=models.DateTimeField(validators=[downtimes.validators.check_date], verbose_name='Дата и время начала работ'),
        ),
    ]
