# Generated by Django 5.2.5 on 2025-12-18 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0004_downtime_link_task_alter_downtime_end_downtime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtime',
            options={'ordering': ('start_downtime',), 'verbose_name': 'Проведение работ на сервисе', 'verbose_name_plural': 'Проведение работ на сервисе'},
        ),
        migrations.AddField(
            model_name='downtime',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtimes_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.CreateModel(
            name='ReminderDowntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_reminder', models.DateTimeField(verbose_name='Первое уведомление')),
                ('second_reminder', models.DateTimeField(blank=True, null=True, verbose_name='Второе уведомление')),
                ('success_reminder', models.BooleanField(default=False, verbose_name='Уведомления отправлены')),
                ('downtime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='downtimes.downtime', verbose_name='Плановая работа')),
            ],
        ),
    ]
