# Generated by Django 5.2.5 on 2026-01-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0004_alter_downtime_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderdowntime',
            name='success_reminder',
            field=models.BooleanField(default=False, verbose_name='Уведомления отправлено в Redis'),
        ),
    ]
