# Generated by Django 5.2.5 on 2025-12-18 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0004_downtime_link_task_alter_downtime_end_downtime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtime',
            options={'ordering': ('start_downtime',), 'verbose_name': 'Проведение работ на сервисе', 'verbose_name_plural': 'Проведение работ на сервисе'},
        ),
        migrations.CreateModel(
            name='ReminderDowntime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_reminder', models.DateTimeField(verbose_name='Первое уведомление')),
                ('second_reminder', models.DateTimeField(blank=True, null=True, verbose_name='Второе уведомление')),
                ('success_reminder', models.BooleanField(default=False, verbose_name='Уведомления отправлены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано от')),
                ('downtime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='downtimes.downtime', verbose_name='Плановая работа')),
            ],
            options={
                'verbose_name': 'Напоминание по проведению работ',
                'verbose_name_plural': 'Напоминания по проведению работ',
            },
        ),
    ]
