# Generated by Django 5.2.5 on 2026-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0005_alter_reminderdowntime_success_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
