# Generated by Django 5.2.5 on 2025-12-18 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0005_alter_downtime_options_downtime_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderdowntime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано от'),
            preserve_default=False,
        ),
    ]
