# Generated by Django 5.2.5 on 2025-12-18 07:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0006_reminderdowntime_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderdowntime',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
