# Generated by Django 5.2.5 on 2025-08-27 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupjob',
            name='employees',
        ),
        migrations.AddField(
            model_name='groupjob',
            name='employees',
            field=models.ManyToManyField(related_name='groupsjob', to=settings.AUTH_USER_MODEL),
        ),
    ]
