# Generated by Django 5.2.5 on 2025-08-27 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_groupjob_employees_groupjob_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupjob',
            name='employees',
            field=models.ManyToManyField(related_name='groupsjob', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
