# Generated by Django 5.2.5 on 2025-08-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_groupjob_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupjob',
            options={'verbose_name': 'Рабочая группа', 'verbose_name_plural': 'Рабочие группы'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
