# Generated by Django 5.2.5 on 2025-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_groupjob_options_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupjob',
            name='employees',
        ),
        migrations.AddField(
            model_name='user',
            name='group_job',
            field=models.ManyToManyField(related_name='users', to='users.groupjob', verbose_name='Группа сотрудника'),
        ),
    ]
