# Generated by Django 5.2.5 on 2025-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_groupjob_employees_user_group_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Босс этой качалки'),
        ),
    ]
