# Generated by Django 5.2.5 on 2026-01-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_job',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.groupjob', verbose_name='Группа сотрудника'),
        ),
    ]
