# Generated by Django 5.2.5 on 2026-02-01 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_departmentjob_groupjob_department_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupjob',
            options={'ordering': ('id',), 'verbose_name': 'Рабочая группа', 'verbose_name_plural': 'Рабочие группы'},
        ),
        migrations.AlterField(
            model_name='departmentjob',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_job', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель'),
        ),
    ]
