# Generated by Django 5.2.5 on 2025-08-27 15:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_workshifts_date_end_workshifts_date_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='date_start',
        ),
        migrations.AddField(
            model_name='holiday',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 8, 27, 15, 3, 54, 753648, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='employee',
        ),
        migrations.CreateModel(
            name='EmployeeHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_day', models.PositiveSmallIntegerField(verbose_name='Количество дней отпуска')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeholidays', to=settings.AUTH_USER_MODEL)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeholidays', to='lk.holiday')),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='employee',
            field=models.ManyToManyField(related_name='holidays', through='lk.EmployeeHoliday', to=settings.AUTH_USER_MODEL),
        ),
    ]
