# Generated by Django 5.2.5 on 2025-08-27 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0003_remove_holiday_date_end_remove_holiday_date_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='date',
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.DeleteModel(
            name='EmployeeHoliday',
        ),
        migrations.AddField(
            model_name='holiday',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays', to=settings.AUTH_USER_MODEL),
        ),
    ]
