# Generated by Django 5.2.5 on 2025-08-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0004_remove_holiday_employee_remove_holiday_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='workshifts',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='workshifts',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
    ]
