# Generated by Django 5.2.5 on 2025-08-29 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0005_holiday_time_end_holiday_time_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Отпуск', 'verbose_name_plural': 'Отпуска'},
        ),
        migrations.AlterModelOptions(
            name='workshifts',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AddField(
            model_name='holiday',
            name='count_day',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во дней'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='status',
            field=models.CharField(choices=[('Запланирован', 'Запланирован'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Завершен', max_length=15, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holiday',
            name='type',
            field=models.CharField(default='Ежегодный', max_length=50, verbose_name='Тип отпуска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshifts',
            name='type',
            field=models.CharField(choices=[('Сменный', 'Сменный'), ('5/2', '5/2')], default='Сменный', max_length=7, verbose_name='Тип графика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshifts',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshifts', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
