# Generated by Django 5.2.5 on 2025-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0006_alter_holiday_options_alter_workshifts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='type',
            field=models.CharField(choices=[('Отпуск без сохранения заработной платы', 'Отпуск без сохранения заработной платы'), ('Ежегодный оплачиваемый отпуск', 'Ежегодный оплачиваемый отпуск')], max_length=50, verbose_name='Тип отпуска'),
        ),
    ]
