# Generated by Django 5.2.5 on 2025-09-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0007_alter_holiday_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='time_start',
        ),
    ]
