# Generated by Django 4.2 on 2025-09-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0008_remove_holiday_time_end_remove_holiday_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='count_day',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во дней'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='type',
            field=models.CharField(choices=[('Отпуск без сохранения заработной платы', 'Отпуск без сохранения заработной платы'), ('Ежегодный оплачиваемый', 'Ежегодный оплачиваемый')], max_length=50, verbose_name='Тип отпуска'),
        ),
    ]
