# Generated by Django 4.2 on 2025-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0009_alter_holiday_count_day_alter_holiday_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='date_end',
        ),
        migrations.AlterField(
            model_name='holiday',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
