# Generated by Django 4.2 on 2025-09-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0010_remove_holiday_date_end_alter_holiday_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='date_start',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='count_day',
        ),
    ]
