# Generated by Django 4.2 on 2025-09-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0011_rename_date_start_holiday_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ('date',), 'verbose_name': 'Отпуск', 'verbose_name_plural': 'Отпуска'},
        ),
        migrations.AlterModelOptions(
            name='workshifts',
            options={'ordering': ('date_start',), 'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('date', 'employee'), name='unique_holidays'),
        ),
        migrations.AddConstraint(
            model_name='workshifts',
            constraint=models.UniqueConstraint(fields=('date_start', 'date_end', 'employee'), name='unique_shifts'),
        ),
    ]
