# Generated by Django 5.2.5 on 2025-10-03 21:18

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0013_alter_workshifts_options_alter_holiday_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 3, 21, 18, 46, 608987, tzinfo=datetime.timezone.utc), verbose_name='Дата обновления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshifts',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='status',
            field=models.CharField(choices=[('Запланирован', 'Запланирован'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='type',
            field=models.CharField(choices=[('Отпуск без сохранения заработной платы', 'Отпуск без сохранения заработной платы'), ('Ежегодный оплачиваемый', 'Ежегодный оплачиваемый')], max_length=50, verbose_name='Тип отпуска'),
        ),
        migrations.AlterField(
            model_name='workshifts',
            name='type',
            field=models.CharField(choices=[('Сменный', 'Сменный'), ('5/2', '5/2')], max_length=7, verbose_name='Тип графика'),
        ),
    ]
