# Generated by Django 5.2.5 on 2025-10-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0014_holiday_updated_at_workshifts_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='status',
            field=models.CharField(blank=True, choices=[('Запланирован', 'Запланирован'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], max_length=15, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='type',
            field=models.CharField(blank=True, choices=[('Отпуск без сохранения заработной платы', 'Отпуск без сохранения заработной платы'), ('Ежегодный оплачиваемый', 'Ежегодный оплачиваемый')], max_length=50, null=True, verbose_name='Тип отпуска'),
        ),
        migrations.AlterField(
            model_name='workshifts',
            name='type',
            field=models.CharField(blank=True, choices=[('Сменный', 'Сменный'), ('5/2', '5/2')], max_length=7, null=True, verbose_name='Тип графика'),
        ),
    ]
