# Generated by Django 5.2.5 on 2026-01-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0015_alter_holiday_status_alter_holiday_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ('-date',), 'verbose_name': 'Отпуск', 'verbose_name_plural': 'Отпуска'},
        ),
        migrations.AlterModelOptions(
            name='workshifts',
            options={'ordering': ('-date_start',), 'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
    ]
