# Generated by Django 5.2.5 on 2026-01-18 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0016_alter_holiday_options_alter_workshifts_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workshifts',
            name='unique_shifts',
        ),
        migrations.AddConstraint(
            model_name='workshifts',
            constraint=models.UniqueConstraint(fields=('date_start', 'employee'), name='unique_shifts'),
        ),
    ]
