# Generated by Django 5.2.5 on 2026-01-18 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0017_remove_workshifts_unique_shifts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshifts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 18, 22, 21, 44, 655869, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshifts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
