# Generated by Django 5.2.5 on 2026-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0018_workshifts_created_at_alter_workshifts_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshifts',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип графика'),
        ),
    ]
